export enum EPOSPrintRecMessageTypeEnum {
  ADDITIONAL_HEADER = '1',
  TRAILER = '2',
  ADDITIONAL_TRAILER = '3',
  ADDITIONAL_DESCRIPTION = '4',
  CUSTOMER_ID = '7',
  PRINT_OR_ERASE_EFT_POS = '8',
}
