export enum EPOSPrintRecAdjustmentTypeEnum {
  DISCOUNT_ON_SUBTOTAL_WITH_SUBTOTAL_PRINTED = '1',
  DISCOUNT_ON_SUBTOTAL_WITHOUT_SUBTOTAL_PRINTED = '2',
  SURCHARGE_ON_SUBTOTAL_WITH_SUBTOTAL_PRINTED = '6',
  SURCHARGE_ON_SUBTOTAL_WITHOUT_SUBTOTAL_PRINTED = '7',
}
